import pandas as pd

def Gorkin2020_pval_accession_all():
    cols = ['signal_p_val_rep1_accession', 'signal_p_val_rep2_accession']
    df = pd.read_csv('Gorkin2020/Supplementary_Table_13.tsv', sep='\t')
    return df[cols].values.flatten()[:20]

rule all:
    # snakemake --cores all --dry-run
    input:
        expand("Gorkin2020/signal_pval/{Accession}.bw", Accession=Gorkin2020_pval_accession_all())

rule Gorkin2020_pval:
    output:
        bw = "Gorkin2020/signal_pval/{Accession}.bw"
    params:
        url = lambda wc: f"https://www.encodeproject.org/files/{wc.Accession}/@@download/{wc.Accession}.bigWig",
    shell: """
        wget --content-disposition -O {output.bw} {params.url}
    """
